### ISSUE TITLE
PHP 7.2 support?

### ISSUE THREAD

**Issue by hws47a** [boesing/captainhook-vendor-resolver#7]
Hi @boesing,

Is it possible to set  PHP 7.2 as a minimum requirement for the package?
It's still officially supported and some of my projects do still use it.

**Comment by boesing** [comment]
Hey @hws47a,

I've created this package earlier this year while PHP 7.2 support was dropped in november 2019, as  you can see [here](https://www.php.net/supported-versions.php)

If you want to use this package in PHP 7.2, feel free to fork it and change the requirements. I think it would work with PHP 7.2.

If you dont want to fork, just use the less secure "import" logic from captainhook directly until you upgraded to 7.3+.
